// core/theme.rs
//
// Window-decoration color themes for the Neutron CSD frame. Premiere's self-drawn
// non-client frame (title bar + menu bar + caption buttons) is themed entirely by
// the Wine prefix's HKCU\Control Panel\Colors, so a "theme" here is just a set of
// those color values. This module is the single source of truth for the built-in
// presets and turns a color set into the .reg text that core/decoration.rs imports
// into the prefix on launch.
//
// Caption-button states map onto these colors (see neutron-wine
// neutron-caption-buttons): ActiveTitle = normal button bg, ButtonShadow = pressed,
// ButtonHilight = min/max hover, ButtonText = glyph. The close-hover red is hardcoded
// in the wine patch (intentional, like Windows) and is NOT themeable here.

use crate::core::settings::Settings;
use std::collections::BTreeMap;

/// A color set: Control Panel color key -> "R G B" (the format Wine expects).
/// BTreeMap keeps the generated .reg deterministic (stable key order).
pub type ColorMap = BTreeMap<String, String>;

/// Built-in preset ids, in display order. ("match-system" lands in M4.)
pub const PRESET_IDS: &[&str] = &["dark", "light"];

/// Human label for a preset id (for the Preferences dropdown).
pub fn preset_label(id: &str) -> &'static str {
    match id {
        "dark" => "Dark",
        "light" => "Light",
        "custom" => "Custom",
        _ => "Dark",
    }
}

/// The color map for a built-in preset id, or None if unknown ("custom" is not a
/// preset — its colors live in Settings).
pub fn preset(id: &str) -> Option<ColorMap> {
    match id {
        "dark" => Some(dark()),
        "light" => Some(light()),
        _ => None,
    }
}

/// The active color map for the given settings: the user's custom colors when
/// theme == "custom" (and non-empty), otherwise the named preset, falling back to
/// Dark for any unknown/missing value. Always returns a usable map.
pub fn active_colors(s: &Settings) -> ColorMap {
    if s.theme == "custom" {
        if let Some(c) = &s.custom_colors {
            if !c.is_empty() {
                // Fill any keys the custom set is missing from Dark, so a partial
                // custom theme can never leave a color unset.
                let mut base = dark();
                base.extend(c.clone());
                return base;
            }
        }
    }
    preset(&s.theme).unwrap_or_else(dark)
}

/// Generate REGEDIT4 text setting HKCU\Control Panel\Colors from a color map,
/// and switching the visual style OFF so those colors actually reach the controls.
/// Matches the format core/decoration.rs imports with `wine regedit`.
///
/// # Why this also writes ThemeActive=0
///
/// ⚠️ Terminology: this is the **default Neutron theme** — the dark chrome the whole stack
/// presents. Collider is one surface that serializes and applies it; it does not own it. Do not
/// call it "Collider's theme".
///
/// A prefix runs TWO independent theming systems, and until 2026-09-11 we drove only one:
///
///  1. `HKCU\Control Panel\Colors` — the classic palette, what this function writes. Anything
///     painted through `GetSysColor` follows it.
///  2. A **visual style** (`.msstyles`). `comdlg32` ships a manifest requiring
///     `Microsoft.Windows.Common-Controls 6.0.0.0`, so its controls are comctl32 v6, and
///     `comctl32_v6/button.c` paints via `PB_ThemedPaint` whenever `GetWindowTheme()` returns a
///     theme — never consulting `GetSysColor` at all.
///
/// **Upstream Wine turns a visual style on in every prefix**: `loader/wine.inf.in` §`[ThemeManager]`
/// sets `ThemeActive=1` against the `aero.msstyles` Wine itself ships. Aero carries its own colour
/// table and it is Windows-default light. So every v6-themed control ignored the Neutron theme and
/// rendered light — on every prefix, on every machine, since the first boot.
///
/// Measured A/B on one throwaway prefix, one variable, sampled by pixel:
///
/// | sample              | ThemeActive=1 | ThemeActive=0 |
/// |---------------------|---------------|---------------|
/// | Open button face    | 255,255,255   | 43,43,43      |
/// | Cancel button face  | 194,194,194   | 86,86,86      |
/// | column header       | 255,255,255   | 43,43,43      |
/// | dialog background   | 43,43,43      | 43,43,43      |
/// | list background     | 43,43,43      | 43,43,43      |
/// | filename edit       | 43,43,43      | 43,43,43      |
///
/// Only the controls that were ignoring the palette changed; everything already correct was
/// untouched. Turning the style off makes v6 controls fall back to classic painting, which reads
/// the colours immediately above.
pub fn reg_text(colors: &ColorMap) -> String {
    let mut out = String::from(
        "REGEDIT4\r\n\r\n\
         ; Generated by Collider (core/theme.rs) — Neutron decoration colors.\r\n\
         [HKEY_CURRENT_USER\\Control Panel\\Colors]\r\n",
    );
    for (k, v) in colors {
        out.push_str(&format!("\"{k}\"=\"{v}\"\r\n"));
    }
    out.push_str(
        "\r\n; Wine's wine.inf enables the bundled Aero visual style in every prefix, and\r\n\
         ; comctl32 v6 controls then paint from IT rather than the palette above.\r\n\
         ; Switch it off so the theme we just wrote actually reaches them.\r\n\
         [HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\ThemeManager]\r\n\
         \"ThemeActive\"=\"0\"\r\n",
    );
    out
}

fn map(pairs: &[(&str, &str)]) -> ColorMap {
    pairs.iter().map(|(k, v)| (k.to_string(), v.to_string())).collect()
}

/// Dark preset — the Neutron default. Matches the original bundled
/// neutron-premiere-dark.reg (dark chrome + flat-button palette).
pub fn dark() -> ColorMap {
    map(&[
        // title bar
        ("ActiveTitle", "43 43 43"),
        ("GradientActiveTitle", "43 43 43"),
        ("TitleText", "224 224 224"),
        ("InactiveTitle", "32 32 32"),
        ("GradientInactiveTitle", "32 32 32"),
        ("InactiveTitleText", "140 140 140"),
        ("ActiveBorder", "43 43 43"),
        ("InactiveBorder", "32 32 32"),
        ("WindowFrame", "20 20 20"),
        // menu bar
        ("Menu", "43 43 43"),
        ("MenuText", "224 224 224"),
        ("MenuBar", "43 43 43"),
        ("MenuHilight", "64 64 64"),
        // window / general
        ("Window", "43 43 43"),
        ("WindowText", "224 224 224"),
        ("HilightText", "255 255 255"),
        // dialogs & controls — the surfaces Wine draws for MESSAGE BOXES, common dialogs and
        // any control an app does not draw itself. Themed, deliberately: the whole point is that
        // a popup matches the rest of the dark UI.
        //
        // ⚠️ These no longer touch the chrome. The caption buttons, the window frame and the rule
        // under the menu bar used to read COLOR_BTNTEXT/BTNHIGHLIGHT/BTNSHADOW/3DFACE, which
        // coupled the title bar to this group; neutron-wine patches zzzzzzzzzp/q/r moved them
        // onto the caption, border and menu colours. So this group is now free to be exactly what
        // its name says, and darkening it cannot put a white border anywhere.
        ("ButtonFace", "43 43 43"),
        ("ButtonHilight", "60 60 60"),
        ("ButtonLight", "50 50 50"),
        ("ButtonShadow", "30 30 30"),
        ("ButtonDkShadow", "16 16 16"),
        ("ButtonText", "224 224 224"),
        ("3DLight", "60 60 60"),
        ("3DDarkShadow", "20 20 20"),
    ])
}

/// Light preset — a clean light chrome (same key set as Dark so switching is total).
pub fn light() -> ColorMap {
    map(&[
        // title bar
        ("ActiveTitle", "245 245 245"),
        ("GradientActiveTitle", "245 245 245"),
        ("TitleText", "20 20 20"),
        ("InactiveTitle", "235 235 235"),
        ("GradientInactiveTitle", "235 235 235"),
        ("InactiveTitleText", "120 120 120"),
        ("ActiveBorder", "245 245 245"),
        ("InactiveBorder", "235 235 235"),
        ("WindowFrame", "180 180 180"),
        // menu bar
        ("Menu", "245 245 245"),
        ("MenuText", "20 20 20"),
        ("MenuBar", "245 245 245"),
        ("MenuHilight", "210 210 210"),
        // window / general
        ("Window", "255 255 255"),
        ("WindowText", "20 20 20"),
        ("HilightText", "255 255 255"),
        // dialogs & controls — see the note in dark(); these are app-facing surfaces, not chrome.
        ("ButtonFace", "245 245 245"),
        ("ButtonHilight", "255 255 255"),
        ("ButtonLight", "235 235 235"),
        ("ButtonShadow", "160 160 160"),
        ("ButtonDkShadow", "120 120 120"),
        ("ButtonText", "20 20 20"),
        ("3DLight", "235 235 235"),
        ("3DDarkShadow", "120 120 120"),
    ])
}
