// core/theme.rs
//
// Window-decoration color themes for the Neutron CSD frame. Premiere's self-drawn
// non-client frame (title bar + menu bar + caption buttons) is themed entirely by
// the Wine prefix's HKCU\Control Panel\Colors, so a "theme" here is just a set of
// those color values. This module is the single source of truth for the built-in
// presets and turns a color set into the .reg text that core/decoration.rs imports
// into the prefix on launch.
//
// Caption-button states map onto these colors (see neutron-wine
// neutron-caption-buttons): ActiveTitle = normal button bg, ButtonShadow = pressed,
// ButtonHilight = min/max hover, ButtonText = glyph. The close-hover red is hardcoded
// in the wine patch (intentional, like Windows) and is NOT themeable here.

use crate::core::settings::Settings;
use std::collections::BTreeMap;

/// A color set: Control Panel color key -> "R G B" (the format Wine expects).
/// BTreeMap keeps the generated .reg deterministic (stable key order).
pub type ColorMap = BTreeMap<String, String>;

/// Built-in preset ids, in display order. ("match-system" lands in M4.)
pub const PRESET_IDS: &[&str] = &["dark", "light"];

/// Human label for a preset id (for the Preferences dropdown).
pub fn preset_label(id: &str) -> &'static str {
    match id {
        "dark" => "Dark",
        "light" => "Light",
        "custom" => "Custom",
        _ => "Dark",
    }
}

/// The color map for a built-in preset id, or None if unknown ("custom" is not a
/// preset — its colors live in Settings).
pub fn preset(id: &str) -> Option<ColorMap> {
    match id {
        "dark" => Some(dark()),
        "light" => Some(light()),
        _ => None,
    }
}

/// The active color map for the given settings: the user's custom colors when
/// theme == "custom" (and non-empty), otherwise the named preset, falling back to
/// Dark for any unknown/missing value. Always returns a usable map.
pub fn active_colors(s: &Settings) -> ColorMap {
    if s.theme == "custom" {
        if let Some(c) = &s.custom_colors {
            if !c.is_empty() {
                // Fill any keys the custom set is missing from Dark, so a partial
                // custom theme can never leave a color unset.
                let mut base = dark();
                base.extend(c.clone());
                return base;
            }
        }
    }
    preset(&s.theme).unwrap_or_else(dark)
}

/// Generate REGEDIT4 text setting HKCU\Control Panel\Colors from a color map.
/// Matches the format core/decoration.rs imports with `wine regedit`.
pub fn reg_text(colors: &ColorMap) -> String {
    let mut out = String::from(
        "REGEDIT4\r\n\r\n\
         ; Generated by Collider (core/theme.rs) — Neutron decoration colors.\r\n\
         [HKEY_CURRENT_USER\\Control Panel\\Colors]\r\n",
    );
    for (k, v) in colors {
        out.push_str(&format!("\"{k}\"=\"{v}\"\r\n"));
    }
    out
}

fn map(pairs: &[(&str, &str)]) -> ColorMap {
    pairs.iter().map(|(k, v)| (k.to_string(), v.to_string())).collect()
}

/// Dark preset — the Neutron default. Matches the original bundled
/// neutron-premiere-dark.reg (dark chrome + flat-button palette).
pub fn dark() -> ColorMap {
    map(&[
        // title bar
        ("ActiveTitle", "43 43 43"),
        ("GradientActiveTitle", "43 43 43"),
        ("TitleText", "224 224 224"),
        ("InactiveTitle", "32 32 32"),
        ("GradientInactiveTitle", "32 32 32"),
        ("InactiveTitleText", "140 140 140"),
        ("ActiveBorder", "43 43 43"),
        ("InactiveBorder", "32 32 32"),
        ("WindowFrame", "20 20 20"),
        // menu bar
        ("Menu", "43 43 43"),
        ("MenuText", "224 224 224"),
        ("MenuBar", "43 43 43"),
        ("MenuHilight", "64 64 64"),
        // window / general
        ("Window", "43 43 43"),
        ("WindowText", "224 224 224"),
        ("HilightText", "255 255 255"),
        // control surfaces — WINDOWS' OWN VALUES, in BOTH presets, on purpose.
        //
        // Real Windows never darkens the classic palette: COLOR_3DFACE is 0xF0F0F0 even in dark
        // mode. Applications are entitled to treat it as a light surface and pair it with their
        // own dark text, and they do -- Lightroom's About box sets black text on its labels and
        // leaves the background to the system, so a dark ButtonFace rendered them black on
        // near-black. Measured: a plain static paints exactly COLOR_BTNFACE behind its text
        // (preserved-fixes/harnesses/sysface-static-bg.c in the neutron repo).
        //
        // The caption buttons used to be the reason these had to be dark. They now take their
        // hover/pressed shades and glyph colour from the CAPTION palette instead -- neutron-wine
        // patch neutron-zzzzzzzzzp-caption-buttons-use-caption-palette -- so nothing in the
        // chrome depends on these any more. ⚠️ Do not re-darken them without checking that.
        ("ButtonFace", "240 240 240"),
        ("ButtonHilight", "255 255 255"),
        ("ButtonLight", "227 227 227"),
        ("ButtonShadow", "160 160 160"),
        ("ButtonDkShadow", "105 105 105"),
        ("ButtonText", "0 0 0"),
        ("3DLight", "227 227 227"),
        ("3DDarkShadow", "105 105 105"),
    ])
}

/// Light preset — a clean light chrome (same key set as Dark so switching is total).
pub fn light() -> ColorMap {
    map(&[
        // title bar
        ("ActiveTitle", "245 245 245"),
        ("GradientActiveTitle", "245 245 245"),
        ("TitleText", "20 20 20"),
        ("InactiveTitle", "235 235 235"),
        ("GradientInactiveTitle", "235 235 235"),
        ("InactiveTitleText", "120 120 120"),
        ("ActiveBorder", "245 245 245"),
        ("InactiveBorder", "235 235 235"),
        ("WindowFrame", "180 180 180"),
        // menu bar
        ("Menu", "245 245 245"),
        ("MenuText", "20 20 20"),
        ("MenuBar", "245 245 245"),
        ("MenuHilight", "210 210 210"),
        // window / general
        ("Window", "255 255 255"),
        ("WindowText", "20 20 20"),
        ("HilightText", "255 255 255"),
        // control surfaces — WINDOWS' OWN VALUES, in BOTH presets, on purpose.
        //
        // Real Windows never darkens the classic palette: COLOR_3DFACE is 0xF0F0F0 even in dark
        // mode. Applications are entitled to treat it as a light surface and pair it with their
        // own dark text, and they do -- Lightroom's About box sets black text on its labels and
        // leaves the background to the system, so a dark ButtonFace rendered them black on
        // near-black. Measured: a plain static paints exactly COLOR_BTNFACE behind its text
        // (preserved-fixes/harnesses/sysface-static-bg.c in the neutron repo).
        //
        // The caption buttons used to be the reason these had to be dark. They now take their
        // hover/pressed shades and glyph colour from the CAPTION palette instead -- neutron-wine
        // patch neutron-zzzzzzzzzp-caption-buttons-use-caption-palette -- so nothing in the
        // chrome depends on these any more. ⚠️ Do not re-darken them without checking that.
        ("ButtonFace", "240 240 240"),
        ("ButtonHilight", "255 255 255"),
        ("ButtonLight", "227 227 227"),
        ("ButtonShadow", "160 160 160"),
        ("ButtonDkShadow", "105 105 105"),
        ("ButtonText", "0 0 0"),
        ("3DLight", "227 227 227"),
        ("3DDarkShadow", "105 105 105"),
    ])
}
